# Generated by Django 4.2.20 on 2025-04-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PlayerFirstName', models.CharField(max_length=50)),
                ('PlayerLastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=2)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TournamentNumber', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=2)),
                ('Date', models.DateField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerNumber', models.IntegerField()),
                ('ClassificationValue', models.IntegerField()),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.player')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.team'),
        ),
    ]
