# Generated by Django 4.2.20 on 2025-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team__city', 'team__name', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-year', 'tournament_number']},
        ),
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'ordering': ['-tournament__year', 'tournament__tournament_number', 'player__team__city', 'player__team__name', 'player__last_name', 'player__first_name']},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='PlayerFirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='PlayerLastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='TeamName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='TournamentNumber',
            new_name='tournament_number',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='Year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='tournamentplayer',
            old_name='ClassificationValue',
            new_name='classification_value',
        ),
        migrations.RenameField(
            model_name='tournamentplayer',
            old_name='Player',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='tournamentplayer',
            old_name='PlayerNumber',
            new_name='player_number',
        ),
        migrations.RenameField(
            model_name='tournamentplayer',
            old_name='Tournament',
            new_name='tournament',
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
