# Generated by Django 4.2.20 on 2025-04-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0002_alter_player_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-year', '-number']},
        ),
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'ordering': ['-tournament__year', 'tournament__number', 'player__team__city', 'player__team__name', 'player__last_name', 'player__first_name']},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_number',
            new_name='number',
        ),
    ]
