# Generated by Django 4.2.20 on 2025-05-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0003_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.stats')),
                ('tournament_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.tournamentplayer')),
            ],
            options={
                'ordering': ['-tournament_player__tournament__year', 'tournament_player__tournament__city', 'tournament_player__player__team__city', 'tournament_player__player__team__name', 'stat__name', 'tournament_player__player_number'],
            },
        ),
    ]
