# Generated by Django 4.2.20 on 2025-05-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0004_stats_playerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.team')),
            ],
            options={
                'ordering': ['-tournament_player__tournament__year', 'tournament_player__tournament__city', 'tournament_player__player__team__city', 'tournament_player__player__team__name', 'stat__name', 'tournament_player__player_number'],
            },
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.stat'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='tournament_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.tournamentplayer'),
        ),
    ]
