# Generated by Django 4.2.20 on 2025-05-08 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0005_playerstat_rename_stats_stat_delete_playerstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='slug',
            field=models.SlugField(),
            preserve_default=False,
        ),
    ]
