# Generated by Django 4.2.20 on 2025-05-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0006_playerstat_created_stat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
