# Generated by Django 4.2.20 on 2025-05-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0007_stat_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='active',
            new_name='is_active',
        ),
    ]
