# Generated by Django 4.2.20 on 2025-08-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0010_player_created_player_updated_playerstat_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_classifications.player')),
            ],
            options={
                'ordering': ['player__team__city', 'player__team__name', 'player__last_name', 'player__first_name'],
            },
        ),
    ]
