# Generated by Django 4.2.20 on 2025-08-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_classifications', '0011_veteran'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team_id'], name='ix_players__team_id'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['slug'], name='ix_team__slug'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['slug'], name='ix_tournament__slug'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament_id', 'player_id'], name='ix_tp__tid_pid'),
        ),
    ]
